# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWidget.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 450)
        Form.setMinimumSize(QtCore.QSize(600, 450))
        Form.setMaximumSize(QtCore.QSize(600, 450))
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(30, 60, 541, 361))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 20, 283, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pB_read = QtWidgets.QPushButton(self.layoutWidget)
        self.pB_read.setMinimumSize(QtCore.QSize(60, 25))
        self.pB_read.setMaximumSize(QtCore.QSize(60, 25))
        self.pB_read.setObjectName("pB_read")
        self.horizontalLayout.addWidget(self.pB_read)
        self.pB_Add = QtWidgets.QPushButton(self.layoutWidget)
        self.pB_Add.setMinimumSize(QtCore.QSize(25, 25))
        self.pB_Add.setMaximumSize(QtCore.QSize(25, 25))
        self.pB_Add.setObjectName("pB_Add")
        self.horizontalLayout.addWidget(self.pB_Add)
        self.pB_Del = QtWidgets.QPushButton(self.layoutWidget)
        self.pB_Del.setMinimumSize(QtCore.QSize(25, 25))
        self.pB_Del.setMaximumSize(QtCore.QSize(25, 25))
        self.pB_Del.setObjectName("pB_Del")
        self.horizontalLayout.addWidget(self.pB_Del)
        self.pB_AllClean = QtWidgets.QPushButton(self.layoutWidget)
        self.pB_AllClean.setMinimumSize(QtCore.QSize(25, 25))
        self.pB_AllClean.setMaximumSize(QtCore.QSize(25, 25))
        self.pB_AllClean.setObjectName("pB_AllClean")
        self.horizontalLayout.addWidget(self.pB_AllClean)
        self.pB_return = QtWidgets.QPushButton(self.layoutWidget)
        self.pB_return.setMinimumSize(QtCore.QSize(25, 25))
        self.pB_return.setMaximumSize(QtCore.QSize(25, 25))
        self.pB_return.setObjectName("pB_return")
        self.horizontalLayout.addWidget(self.pB_return)
        self.pB_setPara = QtWidgets.QPushButton(self.layoutWidget)
        self.pB_setPara.setMinimumSize(QtCore.QSize(60, 25))
        self.pB_setPara.setMaximumSize(QtCore.QSize(60, 25))
        self.pB_setPara.setObjectName("pB_setPara")
        self.horizontalLayout.addWidget(self.pB_setPara)
        self.pB_save = QtWidgets.QPushButton(self.layoutWidget)
        self.pB_save.setMinimumSize(QtCore.QSize(25, 25))
        self.pB_save.setMaximumSize(QtCore.QSize(25, 25))
        self.pB_save.setObjectName("pB_save")
        self.horizontalLayout.addWidget(self.pB_save)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "任务项"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "紧急程度"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "重要程度"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "时间系数"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "优先度"))
        self.pB_read.setToolTip(_translate("Form", "<html><head/><body><p>计算优先度并排序</p></body></html>"))
        self.pB_read.setText(_translate("Form", "Read me"))
        self.pB_Add.setToolTip(_translate("Form", "<html><head/><body><p>新增任务</p></body></html>"))
        self.pB_Add.setText(_translate("Form", "+"))
        self.pB_Del.setToolTip(_translate("Form", "删除任务"))
        self.pB_Del.setText(_translate("Form", "-"))
        self.pB_AllClean.setToolTip(_translate("Form", "<html><head/><body><p>清空任务</p></body></html>"))
        self.pB_AllClean.setText(_translate("Form", "X"))
        self.pB_return.setToolTip(_translate("Form", "<html><head/><body><p>撤销清空</p></body></html>"))
        self.pB_return.setText(_translate("Form", "←"))
        self.pB_setPara.setToolTip(_translate("Form", "<html><head/><body><p>计算优先度并排序</p></body></html>"))
        self.pB_setPara.setText(_translate("Form", "RUN"))
        self.pB_save.setToolTip(_translate("Form", "<html><head/><body><p>保存结果</p></body></html>"))
        self.pB_save.setText(_translate("Form", "↓"))
